### ISSUE TITLE
Showing GPS data from arduino in python executable

### ISSUE THREAD

**Issue by LuccasBeckReis** [oangelo/EcologicalSurveillanceRobot#6]
Accomplishing this issue will be abled to make a future route to the hexapod trace and travel, showing its position through a executable in pc or mobile.

**Comment by LuccasBeckReis** [comment]
Used the GPS datasheet to understand the data received in serial port directly connected to the module.
[NEO-6_DataSheet_(GPS.G6-HW-09005).pdf](https://github.com/oangelo/EcologicalSurveillanceRobot/files/229325/NEO-6_DataSheet_.GPS.G6-HW-09005.pdf)

**Comment by LuccasBeckReis** [comment]
at the following video is shown how to change the settings of the GPS module using the software U Center.

Video: [https://www.youtube.com/watch?v=TwhCX0c8Xe0&ebc=ANyPxKpH9nFLh_Z99dSW-Xdew7-3m1M0U_OH8sxWh16Axy6vAs-f2NcuZg7YSI8de-3UnMvA0EZnt5bDXZ6Rt6QLZnIGqPihvw](url)

UCenter Homepage: [https://www.u-blox.com/en/product/u-center-windows](url)

**Comment by LuccasBeckReis** [comment]
Got good results using a demo code, just changing the serialGPSspeed to 9600 and translating the data to show in serial monitor just the coordinates and date of the gps.

NOTE: using in 3.3V and the TinyGPS++ lib!

`#include <TinyGPS++.h>
#include <SoftwareSerial.h>
/*
   This sample sketch demonstrates the normal use of a TinyGPS++ (TinyGPSPlus) object.
   It requires the use of SoftwareSerial, and assumes that you have a
   4800-baud serial GPS device hooked up on pins 4(rx) and 3(tx).
*/
static const int RXPin = 4, TXPin = 3;
static const uint32_t GPSBaud = 9600;

// The TinyGPS++ object
TinyGPSPlus gps;

// The serial connection to the GPS device
SoftwareSerial ss(RXPin, TXPin);

void setup()
{
  Serial.begin(115200);
  ss.begin(GPSBaud);

  Serial.println(F("DeviceExample.ino"));
  Serial.println(F("A simple demonstration of TinyGPS++ with an attached GPS module"));
  Serial.print(F("Testing TinyGPS++ library v. ")); Serial.println(TinyGPSPlus::libraryVersion());
  Serial.println(F("by Mikal Hart"));
  Serial.println();
}

void loop()
{
  // This sketch displays information every time a new sentence is correctly encoded.
  while (ss.available() > 0)
    if (gps.encode(ss.read()))
      displayInfo();

  if (millis() > 5000 && gps.charsProcessed() < 10)
  {
    Serial.println(F("No GPS detected: check wiring."));
    while(true);
  }
}

void displayInfo()
{
  Serial.print(F("Location: ")); 
  if (gps.location.isValid())
  {
    Serial.print(gps.location.lat(), 6);
    Serial.print(F(","));
    Serial.print(gps.location.lng(), 6);
  }
  else
  {
    Serial.print(F("INVALID"));
  }

  Serial.print(F("  Date/Time: "));
  if (gps.date.isValid())
  {
    Serial.print(gps.date.month());
    Serial.print(F("/"));
    Serial.print(gps.date.day());
    Serial.print(F("/"));
    Serial.print(gps.date.year());
  }
  else
  {
    Serial.print(F("INVALID"));
  }

  Serial.print(F(" "));
  if (gps.time.isValid())
  {
    if (gps.time.hour() < 10) Serial.print(F("0"));
    Serial.print(gps.time.hour());
    Serial.print(F(":"));
    if (gps.time.minute() < 10) Serial.print(F("0"));
    Serial.print(gps.time.minute());
    Serial.print(F(":"));
    if (gps.time.second() < 10) Serial.print(F("0"));
    Serial.print(gps.time.second());
    Serial.print(F("."));
    if (gps.time.centisecond() < 10) Serial.print(F("0"));
    Serial.print(gps.time.centisecond());
  }
  else
  {
    Serial.print(F("INVALID"));
  }

  Serial.println();
}`

**Comment by oangelo** [comment]
See #8.
