### ISSUE TITLE
Make a simple user interface to see and get coordinates of a map.

### ISSUE THREAD

**Issue by oangelo** [oangelo/EcologicalSurveillanceRobot#8]
The interface should be in python, because it is very simple to use, and using google maps, since it is the best map api.

**Comment by oangelo** [comment]
I found a nice simple example here: https://www.reddit.com/r/learnpython/comments/2ldevz/python_gui_with_google_maps/.
I created a new branch trip_plan and uploaded the code there.

**Comment by LuccasBeckReis** [comment]
I've just finished a code that receives from arduino the coordinates and split then, converting into both float and string types. The next step is to show these coordinates directly at the GoogleMaps' map.
